default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  pool: 5

development:
  <<: *default
  database: login_thema_lesson_development

test:
  <<: *default
  database: login_thema_lesson_test

production:
  <<: *default
  database: login_thema_lesson_production
  username: login_thema_lesson
  password: <%= ENV['LOGIN_THEMA_LESSON_DATABASE_PASSWORD'] %>
